apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-app
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
        - name: app
          image: restaurant-system:latest
          ports:
            - containerPort: 8080
          env:
            - name: PG_URL
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: PG_URL

